# Generated by Django 3.0.11 on 2021-01-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
