# Generated by Django 3.0.11 on 2021-01-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elenasapp', '0003_auto_20210130_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employer',
            field=models.ForeignKey(blank=True, help_text='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='elenasapp.Employer'),
        ),
    ]
